// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatRoom } from "./ChatRoom";
import type { User } from "./User";

export type ChatMessage = {
  id: string;
  room: ChatRoom | null;
  user: User | null;
  content: string;
  chatRoomId: string;
  userId: string;
  createdAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};
