// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatRoom = {
  id: string;
  name: string;
  roomType: string;
  createdAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};
