// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Country } from "./Country";
import type { Group } from "./Group";
import type { Tournament } from "./Tournament";

export type CountryGroup = {
  id: string;
  tournament: Tournament | null;
  tournamentId: string;
  group: Group | null;
  groupId: string;
  country: Country | null;
  countryId: string;
  isOut: boolean;
  points: number;
  createdAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};
