// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountryGroup } from "./CountryGroup";
import type { Group } from "./Group";
import type { Tournament } from "./Tournament";

export type Country = {
  id: string;
  name: string;
  alpha2: string;
  alpha3: string;
  tournaments: Array<Tournament> | null;
  groups: Array<Group> | null;
  coutryGroup: Array<CountryGroup> | null;
  createdAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};
