// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Country } from "./Country";
import type { GameStatus } from "./GameStatus";
import type { Stage } from "./Stage";
import type { Tournament } from "./Tournament";

export type Game = {
  id: string;
  status: GameStatus;
  stage: Stage;
  label: string;
  count: number;
  tournament: Tournament | null;
  tournamentId: string;
  countryA: Country | null;
  countryB: Country | null;
  countryAId: string;
  countryBId: string;
  penalty: boolean;
  countryAGoals: number;
  countryBGoals: number;
  countryAPenaltyGoals: number;
  countryBPenaltyGoals: number;
  winner: Country | null;
  winnerId: string;
  dateAndTime: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  deletedAt: string | null;
};
