// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Point = {
  userId: string;
  avatar: string;
  username: string;
  totalPoints: number;
  totalTips: number;
  position: number;
};
