// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Stage =
  | "group"
  | "round_32"
  | "round_16"
  | "round_8"
  | "round_4"
  | "third_place"
  | "final";
