// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Strategy } from "./Strategy";
import type { StrategyPoint } from "./StrategyPoint";
import type { TipStrategy } from "./TipStrategy";
import type { Tournament } from "./Tournament";

export type Tip = {
  id: string;
  tournament: Tournament | null;
  tournamentId: string;
  tipStrategy: TipStrategy | null;
  tipStrategyPts: Array<StrategyPoint>;
  tipStrategyId: string;
  userId: string;
  strategies: Array<Strategy>;
  points: number;
  createdAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};
