// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";
import type { StrategyType } from "./StrategyType";
import type { Tournament } from "./Tournament";

export type TipStrategy = {
  game: Game | null;
  tournament: Tournament | null;
  id: string;
  tournamentId: string;
  gameId: string | null;
  label: string;
  description: string;
  opensAt: Date | null;
  endsAt: Date | null;
  calculatePointsOn: Date | null;
  completed: boolean;
  strategyTypes: Array<StrategyType>;
  createdAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};
