// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TournamentStatus } from "./TournamentStatus";

export type Tournament = {
  id: string;
  name: string;
  label: string;
  description: string;
  status: TournamentStatus;
  createdAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};
