// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserData } from "./UserData";

export type User = {
  id: string;
  email: string;
  data: UserData;
  actor: object;
  actorRoles: object;
  authActorId: string;
  createdAt: Date | null;
  updatedAt: Date | null;
  deletedAt: Date | null;
};
