// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CountryGroupPayload = {
  tournamentId: string | null;
  groupId: string | null;
  countryId: string | null;
  isOut: boolean | null;
  points: number;
};
