// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CredentialUpdatePayload = {
  username: string | null;
  email: string | null;
  password: string | null;
};
