// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameStatus } from "../GameStatus";
import type { Stage } from "../Stage";

export type GamePayload = {
  tournamentId: string;
  label: string;
  count: number;
  stage: Stage | null;
  status: GameStatus | null;
  countryAId: string | null;
  countryBId: string | null;
  penalty: boolean | null;
  countryAGoals: number | null;
  countryBGoals: number | null;
  winnerId: string | null;
  toConfigureOn: string | null;
  countryAPenaltyGoals: number | null;
  countryBPenaltyGoals: number | null;
};
