// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameStatus } from "../GameStatus";
import type { Stage } from "../Stage";

export type GameUpdatePayload = {
  label: string;
  count: bigint | null;
  stage: Stage | null;
  status: GameStatus | null;
  countryAId: string;
  countryBId: string;
  penalty: boolean | null;
  countryAGoals: bigint | null;
  countryBGoals: bigint | null;
  winnerId: string;
  toConfigureOn: Date;
};
