// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameStatus } from "../GameStatus";
import type { Stage } from "../Stage";

export type GameCreatePayload = {
  tournamentId: string;
  status: GameStatus;
  stage: Stage;
  label: string;
  count: bigint;
  countryAId: string;
  countryBId: string;
  penalty: boolean;
  toConfigureOn: Date;
};
