// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Strategy } from "../Strategy";

export type TipPayload = {
  id: string | null;
  tipStrategyId: string;
  tournamentId: string;
  userId: string | null;
  strategies: Array<Strategy>;
};
