// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StrategyType } from "../StrategyType";

export type TipStrategyPayload = {
  tournament_id: string;
  label: string;
  description: string;
  game_id: string;
  opens_at: string;
  ends_at: string;
  calculate_points_on: string;
  completed: boolean;
  strategy_types: Array<StrategyType>;
};
