// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StrategyType } from "../StrategyType";

export type TipStrategyPayload = {
  tournamentId: string;
  label: string;
  description: string;
  gameId: string | null;
  groupId: string | null;
  opensAt: string;
  endsAt: string;
  calculatePointsOn: string;
  completed: boolean;
  strategyTypes: Array<StrategyType>;
};
