// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TournamentStatus } from "../TournamentStatus";

export type TournamentPayload = {
  label: string;
  description: string;
  status: TournamentStatus;
};
